// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJj9v2mq20D469cQIeSweAKXV4YUheyg0',
    appId: '1:796844237295:web:e3f5e9d539d9ffaad7d61a',
    messagingSenderId: '796844237295',
    projectId: 'secret-box-ad9f5',
    authDomain: 'secret-box-ad9f5.firebaseapp.com',
    storageBucket: 'secret-box-ad9f5.firebasestorage.app',
    measurementId: 'G-Y8W497FZRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbyNqe7iard8fWGeZVNg_WYtiJhmkgI0',
    appId: '1:796844237295:android:d3297816b7826546d7d61a',
    messagingSenderId: '796844237295',
    projectId: 'secret-box-ad9f5',
    storageBucket: 'secret-box-ad9f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUyTjlxoU5Y5RhnThqCtVf5t6K1o_508Y',
    appId: '1:796844237295:ios:43e4727f20bab23cd7d61a',
    messagingSenderId: '796844237295',
    projectId: 'secret-box-ad9f5',
    storageBucket: 'secret-box-ad9f5.firebasestorage.app',
    iosBundleId: 'com.example.secretBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUyTjlxoU5Y5RhnThqCtVf5t6K1o_508Y',
    appId: '1:796844237295:ios:43e4727f20bab23cd7d61a',
    messagingSenderId: '796844237295',
    projectId: 'secret-box-ad9f5',
    storageBucket: 'secret-box-ad9f5.firebasestorage.app',
    iosBundleId: 'com.example.secretBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJj9v2mq20D469cQIeSweAKXV4YUheyg0',
    appId: '1:796844237295:web:7778a093e48f50bdd7d61a',
    messagingSenderId: '796844237295',
    projectId: 'secret-box-ad9f5',
    authDomain: 'secret-box-ad9f5.firebaseapp.com',
    storageBucket: 'secret-box-ad9f5.firebasestorage.app',
    measurementId: 'G-0K7VKYVWSS',
  );
}
